version: '3'
services:
  backend:
    build: ./homegame  # Path to your backend Dockerfile (homegame directory)
    ports:
      - "8000:8000"  # Adjust port as needed
    volumes:
      - ./homegame/poker.db:/app/poker.db  # Map the poker.db directly
    environment:
      - DATABASE_URL=sqlite:///./poker.db  # Path to poker.db in the container
      - PORT=8000  # Port to run the backend on
      - PYTHON_ENV=production 


  frontend:
    build: ./React  # Path to your frontend Dockerfile
    ports:
      - "3000:3000"  # Adjust port as needed
    depends_on:
      - backend
    environment:
      - NODE_ENV=production 
      - REACT_APP_BE_URL=https://homegame-api.pintopi.nl  # URL to the backend service


